FROM fedora:23

RUN dnf -y install  \
	xcb-util-devel \
	xcb-util-keysyms-devel \
	xcb-util-wm-devel \
	libX11-devel \
	libXcursor-devel \
	libXft-devel \
	libXt-devel \
	libXrandr-devel	\
	make \
	git \
	gcc
